name: Run PyRight

on: [push, pull_request]


jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14
        
      - name: Run type checking
        run: |
          npm install -g pyright
          pip install .
          pyright --lib --verifytypes pytweet --ignoreexternal
